# con esto funciona en local, pero para docker se deben usar las variables de entorno
# spring.application.name=sistema-inventario

# spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/sistema_inventario}
# spring.datasource.username=${DB_USERNAME:postgres}
# spring.datasource.password=${DB_PASSWORD:root}
# spring.datasource.driver-class-name=org.postgresql.Driver

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.open-in-view=false
# spring.jpa.properties.hibernate.jdbc.time_zone=UTC
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# hasta aqui funciona en local, pero para docker se deben usar las variables de entorno
# ///////////////////////////////////////////////
# spring.application.name=sistema-inventario

# # El puerto lo asignará Render automáticamente en producción, si no existe usa el 8080 local
# server.port=${PORT:8080}

# # Variables dinámicas: En tu PC usarán los valores por defecto (localhost, postgres, root)
# # En Render leerán las variables secretas de la nube automáticamente
# spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sistema_inventario}
# spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
# spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
# spring.datasource.driver-class-name=org.postgresql.Driver

# # Configuración limpia de Hibernate para PostgreSQL
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.open-in-view=false
# spring.jpa.properties.hibernate.jdbc.time_zone=UTC
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# //////////////////////////////////////////////////
spring.application.name=sistema-inventario

# El puerto lo asignará Render automáticamente en producción, si no existe usa el 8080 local
server.port=${PORT:8080}

# Variables de entorno personalizadas con nombres únicos para evitar bucles de sobreescritura
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/sistema_inventario}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:root}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración limpia de Hibernate para PostgreSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

